version: "3"

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - ./users-db:/var/lib/postgresql/data
